### ISSUE TITLE
Android 3 button navigation doesn't hide 

### ISSUE THREAD

**Issue by gtaforever00** [Ilan12346-maya/XinputBridge#1]
When the service is active and you press the rectangle in the upper left corner to activate gamepad, the Android 3 button navigation shows and doesn't hide.

Platform: Android 13
Application: Exagear Ajay mod
Wine: 8.2

**Comment by Ilan12346-maya** [comment]
Sorry for replying this late

Should be easy fix, will fix it in next build

**Comment by Ilan12346-maya** [comment]
solved, by Release 1.2

:D
