### ISSUE TITLE
L2 R2 Buttons

### ISSUE THREAD

**Issue by FarsikBarsik** [Ilan12346-maya/XinputBridge#2]
Buttons L2 R2 have only two positions support - on or off with no intermediate positions.

**Comment by ynixt** [comment]
Since we are using the DLLs provided by winlator we have the same limitations that winlator currently have. In other words: For now, L2/R2 are interpreted as buttons and not as triggers.

**Comment by coryrauch** [comment]
Your XinputBridge project is awesome! Keep up the good work!

I wanted to call out on this issue that there is a mod for Winlator that adds support for linear triggers. The repo is here: https://github.com/longjunyu2/winlator/releases/

Maybe it is something that can be ported to your project.
