### ISSUE TITLE
Gamesir x2 pro

### ISSUE THREAD

**Issue by Asket555** [Ilan12346-maya/XinputBridge#4]
After installing the dll and launching it, the gamepad is not visible. Nothing appears in the control panel. Mobox wow64, gamesir x2 pro.

**Comment by ynixt** [comment]
Please confirm if you did all steps:

1. Install DLLs
2. Open the app
3. Click on "Grant permissions" button on app
4. "Click on "start the service" on app
5. A red flag on the top-left border should appear. Click on it to block touch and enable gamepad. If you click again you disable gamepad and enable touch

**Comment by Asket555** [comment]
Still not detected in mobix wiw64. It seems like the controller is not connected.

**Comment by Asket555** [comment]
After several reboots I connected the controller and after launching mobox wow64 everything worked.

**Comment by Ilan12346-maya** [comment]
My Main Gamepad is also an gamesir x2 (non pro) Sometimes the Connector is Not working or the gamesir App Take it 

Or the wrong Mode (Green Led)
