### ISSUE TITLE
Immediately crashes when starting service on Samsung

### ISSUE THREAD

**Issue by dstarikov** [Ilan12346-maya/XinputBridge#6]
The app crashes as soon as I push the button to start the overlay service.
The draw-on-top-of-other-apps permission has been granted to the app.
I am using a ps5 controller connected via USB - it is detected by the gamepad info screen in the app.

This is happening on the latest release as well as the previous one on my Galaxy Z Fold 4, running OneUI 6.0 and Android 14

Here is a logcat I pulled from the crash:

04-22 22:44:12.710 19787 19787 E AndroidRuntime: Process: com.ilan12346.xinputbridge, PID: 19787
04-22 22:44:12.710 19787 19787 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.ilan12346.xinputbridge.OverlayService@277a1ac with Intent { cmp=com.ilan12346.xinputbridge/.OverlayService }: java.lang.ArrayIndexOutOfBoundsException: length=64; index=64
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8913)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
04-22 22:44:12.710 19787 19787 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=64; index=64
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at com.ilan12346.xinputbridge.OverlayService.onStartCommand(Unknown Source:143)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
04-22 22:44:12.710 19787 19787 E AndroidRuntime:        ... 9 more

**Comment by dstarikov** [comment]
Yes. The permission is granted. ![Screenshot_20240423_155302_Settings.jpg](https://github.com/Ilan12346-maya/XinputBridge/assets/18320694/5212892e-ef87-4bfd-a98a-841a0422e8d6)

**Comment by Ilan12346-maya** [comment]
> The app crashes as soon as I push the button to start the overlay service.

Is this also the Case If you fold it and use the Front Screen? 
Thanks for the logcat

**Comment by dstarikov** [comment]
Huh....

I just tried using it when folded closed for the first time and it seems to work - it creates a little purple shaded box in the top left corner when starting the service and goes away when stopping.

After that, it seems to now be working fine in unfolded mode as well.

Haven't had a chance to test with termux yet for input, but I'd expect it to work now.

**Comment by dstarikov** [comment]
On a side note, is there any reason why XinputBridge needs to be a separate app?

This project is building off of the work from this repo, right? [xinput-bridge](https://github.com/quantumrain/xinput-bridge)

I've been thinking about implementing similar project myself, but was thinking to do this directly within termux-x11.

Have you considered trying to integrate this functionality directly into the termux-x11 app itself instead? That would completely eliminate the need for an overlay I imagine.

**Comment by ynixt** [comment]
> On a side note, is there any reason why XinputBridge needs to be a separate app?
> 
> This project is building off of the work from this repo, right? [xinput-bridge](https://github.com/quantumrain/xinput-bridge)
> 
> I've been thinking about implementing similar project myself, but was thinking to do this directly within termux-x11.
> 
> Have you considered trying to integrate this functionality directly into the termux-x11 app itself instead? That would completely eliminate the need for an overlay I imagine.
> 
> Are there any source files or documentation on building `winefiles` for this project?

Currently is on a side project because is easier to made!
You're completely welcome to try to implement directly on x11.
The current DLLs was reused from winlator, [here is the source](https://github.com/brunodev85/winlator/blob/main/wine_patches/dlls/xinput/main.c)

**Comment by Ilan12346-maya** [comment]
It have nothing To-Do with this Project, only Like Same Name 

In Future i will intigration it to termux x11 but at First it should be Rock stable 💪🏻

Working on.

**Comment by Ilan12346-maya** [comment]
Will add termux x11 with XinputBridge intigration later 

![IMG_20240508_044542_904](https://github.com/Ilan12346-maya/XinputBridge/assets/103835810/c26c4000-cb12-4dd1-a63b-d197cb66d656)
