### ISSUE TITLE
Fallout 3 G.O.T.Y Edition GOG Version

### ISSUE THREAD

**Issue by FarsikBarsik** [Ilan12346-maya/XinputBridge#8]
After ~10 minutes controller's input stops with no way to take controls again except by rebooting mobox. 
Another symptom: after ~10 minutes it starts spinning like you're holding analog stick in left (or right) side.

Processor: Snap 8 Gen 2
Gamepad: Dualshock 4
Wine version: 8.18 staging wow64 version, same on 8.18 vanilla

**Comment by Ilan12346-maya** [comment]
This is the Same Problem 

It randomly Stop working on wineside and freezing the Gamepad states 

If you spinnt it keep Spinning 


Iam working on it, in fact this is the Main issue in many Games

**Comment by Ilan12346-maya** [comment]
Fixed with Version 1.2 :D
