### ISSUE TITLE
Does not support wine9.7 and cannot make it effective

### ISSUE THREAD

**Issue by kongmao45678** [Ilan12346-maya/XinputBridge#9]
Does not support wine9.7 and cannot make it effective，It should be a problem with the dll file copied in.

**Comment by Ilan12346-maya** [comment]
I will Try to Compile the dlls for all Major wine builds these days 

The Main issue is maybe the dlls are wine 8.2 based 

Iam working on

**Comment by Ilan12346-maya** [comment]
Compiling it on wine9.3 dosnt solve the Problem 

Will Try other Things

**Comment by Ilan12346-maya** [comment]
works fine here

**Comment by dstarikov** [comment]
Compiled using wine 9.3 and is working on 9.7 and 9.8 for me.

**Comment by Ilan12346-maya** [comment]
> Compiled using wine 9.3 and is working on 9.7 and 9.8 for me.
> Compiling using wine 9.8 also worked for me.
> 

Using my Compile stuff? 😁😁😁

**Comment by dstarikov** [comment]
> > Compiled using wine 9.3 and is working on 9.7 and 9.8 for me.
> > Compiling using wine 9.8 also worked for me.
> 
> Using my Compile stuff? 😁😁😁

Yes - it worked well for me, thanks for providing that!

**Comment by Ilan12346-maya** [comment]
Oh, very nice, I'm proud that someone use this.

**Comment by kongmao45678** [comment]
It is possible to add support for Winlator. Now, it is not possible to connect the controller directly in Winlator, and it needs to be mapped. But using your software, it can achieve direct connection.

**Comment by Ilan12346-maya** [comment]
> It is possible to add support for Winlator. Now, it is not possible to connect the controller directly in Winlator, and it needs to be mapped. But using your software, it can achieve direct connection.

U Sure its not possible? Should Work normal


You can usw my Files without the App, should Work in winlator

**Comment by kongmao45678** [comment]
Wine 9.1 has been tested for support, but wine 9.3 and 9.8 have not been tested successfully.

**Comment by kongmao45678** [comment]
I'll try 1.2 and get back to you.

**Comment by kongmao45678** [comment]
Use version 1.2. After testing, wine9.3 works fine, but wine97 and 98 cannot be used.

**Comment by Stan7827** [comment]
> > Compiled using wine 9.3 and is working on 9.7 and 9.8 for me.
> > Compiling using wine 9.8 also worked for me.
> 
> Using my Compile stuff? 😁😁😁

Working for me too.

**Comment by Ilan12346-maya** [comment]
Will Compile Files for winlator later
